In [ ]:
!python --version
# !pip freeze
import numpy
print(numpy.__version__)

Python 3.12.13
2.0.2


# **1. TWORZENIE I PRZEKSZTAŁCANIE TABLICY**

In [ ]:
import numpy as np

tablica = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"Array: {tablica}")
print(f"Shape of array: {np.shape(tablica)}\n")


tab2x6 = tablica.reshape(2,6)
print(f"Array: {tab2x6}")
print(f"Shape of array: {np.shape(tab2x6)}\n")

# Zadanie: kształty (3,4)  i (2,2,3)
tab3x4 = tablica.reshape(3,4)
print(f"Array: {tab3x4}")
print(f"Shape of array: {np.shape(tab3x4)}\n")

tab2x2x3 = tablica.reshape(2,2,3)
print(f"Array: {tab2x2x3}")
print(f"Shape of array: {np.shape(tab2x2x3)}\n")


print("Zagadka1:")
zagadka1 = tablica.reshape(-1)
print(f"Array: {zagadka1}")
print(f"Shape of array: {np.shape(zagadka1)}\n")

print("Zagadka2:")
zagadka2 = tablica.reshape(6,-1)
print(f"Array: {zagadka2}")
print(f"Shape of array: {np.shape(zagadka2)}\n")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of array: (12,)

Array: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape of array: (2, 6)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array: (3, 4)

Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of array: (2, 2, 3)

Zagadka1:
Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of array: (12,)

Zagadka2:
Array: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape of array: (6, 2)



# **2. SORTOWANIE TABLIC**

In [ ]:
import numpy as np
# 1. Tablica nieposortowana
unsorted1D = np.array([3,6,2,4])
print(f"Nieposortowana tablica: {unsorted1D}")

# 2. Posortowac i wyświetlić
sorted1D = np.sort(unsorted1D)
print(f"Posortowana tablica: {sorted1D}")


# 3. Utworzyć dwuwymiarową tablicę
unsorted2D = np.array([[3,6,2],
                      [4,8,1],
                      [5,6,3]])
print(f"Nieposortowana tablica:\n {unsorted2D}")

# 4. Posortować względem krawedzi 0
sorted2D_axis0 = np.sort(unsorted2D,axis=0)
print(f"Posortowana tablica po axis0:\n {sorted2D_axis0}")

# 5. Posortować względem krawedzi 1
sorted2D_axis1 = np.sort(unsorted2D,axis=1)
print(f"Posortowana tablica po axis1:\n {sorted2D_axis1}")



cities_data = np.array([
    ("Poznań", "Polska", 540000),
    ("Berlin", "Niemcy", 3700000),
    ("Praga", "Czechy", 1300000),
    ("Paryż", "Francja", 2100000),
    ("Rzym", "Włochy", 2800000),
    ("Madryt", "Hiszpania", 3200000),
    ("Wiedeń", "Austria", 1900000)
], dtype=[
    ('City', 'U30'),
    ('Country', 'U30'),
    ('Population', 'i4')
])


# print("Sortowanie po City")
# print(np.sort(cities_data, order='City'))

# print("Sortowanie po państwie")
# print(np.sort(cities_data,order='Country'))


Nieposortowana tablica: [3 6 2 4]
Posortowana tablica: [2 3 4 6]
Nieposortowana tablica:
 [[3 6 2]
 [4 8 1]
 [5 6 3]]
Posortowana tablica po axis0:
 [[3 6 1]
 [4 6 2]
 [5 8 3]]
Posortowana tablica po axis1:
 [[2 3 6]
 [1 4 8]
 [3 5 6]]
Sortowanie po państwie
[('Wiedeń', 'Austria', 1900000) ('Praga', 'Czechy', 1300000)
 ('Paryż', 'Francja', 2100000) ('Madryt', 'Hiszpania', 3200000)
 ('Berlin', 'Niemcy', 3700000) ('Poznań', 'Polska',  540000)
 ('Rzym', 'Włochy', 2800000)]


# **3. LICZBY LOSOWE**

In [23]:
from numpy import random

# random.randint
for i in range(10): # liczby z zakresu od 10 do 20
  print(random.randint(10,21))


#random.rand
for i in range(10): # liczby z zakresu od 0 do 1
  print(random.rand())

15
13
17
17
10
12
10
11
17
10
0.3817466059038894
0.5955898484275713
0.6004240921898243
0.31728577266047897
0.4903653822224008
0.41950949713000085
0.6860985103486005
0.6450009955858227
0.7058417055228192
0.28664777786519


# **4. PRZESZUKIWANIE TABLIC**

In [25]:
# np.where(warunek, wartość_jesli_prawda, wartość_jeśłi fałsz)
import numpy as np

x = np.array([1,5,6,2,10])

wynik = np.where(x > 5, "duże", "małe")
print(wynik)

tab2D =np.array( [[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,6]])

index6 = np.where(tab2D == 6)
print(index6)

['małe' 'małe' 'duże' 'małe' 'duże']
(array([1, 2]), array([0, 4]))


# **5. FILTROWANIE TABLIC**

In [27]:
import numpy as np

array2D = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 6]
])

# Liczby parzyste:

# 1. Maska logiczna
binary_mask = np.where(array2D % 2 == 0, True, False)
print(binary_mask)

# 2. Filtrowanie tablicy maską
filtered = array2D[binary_mask]
print(filtered)

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True  True]]
[ 2  4  6  8 10 12 14  6]


# **6. PO CO MI TO?**

In [42]:
# DEKORATOR
# - funkcja, która przyjmuje inną funkcję jako argument, „opakowuje” ją dodatkowym kodem i zwraca nową wersję tej funkcji
# Czyli dekorator pozwala dodać coś do funkcji bez zmieniania jej kodu
    # mierzenie czasu działania funkcji
    # logowanie
    # sprawdzanie uprawnień
    # obsługę błędów

import time
import numpy as np

def measure_time(func):
  def wrapper(*args, **kwargs):
    start_time = time.time() # Zapisuje czas przed uruchomieniem funkcji
    result = func(*args, **kwargs) # Uruchamia właściwą funkcję, którą dekorujemy
    end_time = time.time() # Zapisuje czas po zakończeniu funkcji

    execution_time = end_time - start_time # Oblicza, ile sekund trwało wykonanie funkcji

    print(f"Funkcja {func.__name__} wykonana w {execution_time:.5f} s") # Wypisuje nazwę funkcji i czas działania
    return execution_time # Zwraca czas wykonania
  return wrapper


# 2.Tworzymy listę i tablicę z milionem elementów (liczbami od 0 do 999 999).
size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)


print(f"\nMnożenie:")
@measure_time
def standard_mult(python_list):
  py_result = [x*2 for x in python_list]

@measure_time
def numpy_mult(numpy_array):
  np_result = numpy_array * 2


time1 = standard_mult(py_list)
time2 = numpy_mult(np_array)
print(f"PRzyśpieszenie przy mnożeniu {time1/time2:.2f}x")



print(f"\nSumowanie:")
@measure_time
def standard_sum(python_list):
  py_sum = sum(python_list)

@measure_time
def numpy_sum(numpy_array):
  np_sum = np.sum(numpy_array)

time1 = standard_sum(py_list)
time2 = numpy_sum(np_array)
print(f"Przyśpieszenie przy dodawaniu {time1/time2:.2f}x")



print(f"\nŚrednia:")
@measure_time
def standard_mean(python_list):
  py_mean = sum(python_list) / len(python_list)

@measure_time
def numpy_mean(numpy_array):
  np_mean = np.mean(numpy_array)

time1 = standard_mean(py_list)
time2 = numpy_mean(np_array)
print(f"Przyśpieszenie przy wyliczaniu średniej {time1/time2:.2f}x")


print(f"\nFiltrowanie:")
@measure_time
def standard_conditional(python_list):
  py_filtered = [x for x in python_list if x > 500_000]

@measure_time
def numpy_conditional(numpy_array):
  np_filtered = np_array[numpy_array > 500_000]

time1 = standard_conditional(py_list)
time2 = numpy_conditional(np_array)
print(f"Przyśpieszenie przy filtrowaniu {time1/time2:.2f}x")


Mnożenie:
Funkcja standard_mult wykonana w 0.06093 s
Funkcja numpy_mult wykonana w 0.00160 s
PRzyśpieszenie przy mnożeniu 38.19x

Sumowanie:
Funkcja standard_sum wykonana w 0.00937 s
Funkcja numpy_sum wykonana w 0.00083 s
Przyśpieszenie przy dodawaniu 11.24x

Średnia:
Funkcja standard_mean wykonana w 0.00950 s
Funkcja numpy_mean wykonana w 0.00132 s
Przyśpieszenie przy wyliczaniu średniej 7.17x

Filtrowanie:
Funkcja standard_conditional wykonana w 0.02668 s
Funkcja numpy_conditional wykonana w 0.00248 s
Przyśpieszenie przy filtrowaniu 10.76x
